# Generated by Django 2.0.4 on 2018-04-19 21:04

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_original', models.TextField()),
                ('name_romaji', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_original', models.TextField()),
                ('title_translated', models.TextField()),
                ('title_romaji', models.TextField()),
                ('lyrics_original', markdownx.models.MarkdownxField()),
                ('lyrics_translated', markdownx.models.MarkdownxField()),
                ('lyrics_romaji', markdownx.models.MarkdownxField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Artist')),
            ],
        ),
    ]
