# Generated by Django 2.0.4 on 2018-04-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics_original',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics_romaji',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics_translated',
            field=models.TextField(),
        ),
    ]
