SLUG_TO_ARTIST = {
    'ai': 'AI',
    'boa': 'BoA',
    'dohzi-t': 'Dohzi-T',
    'gorie-with-jasmine-and-joann': 'Gorie with Jasmine and Joann',
    'larcenciel': 'L\'Arc~en~Ciel',
    'nico-touches-the-walls': 'NICO Touches the Walls',
    'satou-chikuzen-kobukuro': 'Satou Chikuzen & Kobukuro',
    'tacky-tsubasa': 'Tacky & Tsubasa',
    'm-flo': 'm-flo',
    'akb48': 'AKB48',
    'kokia': 'KOKIA',
}

SLUG_TO_SONG_TITLE = {
    'dontleave-me-alone': '(don\'t)Leave Me Alone',
    'kuronekoadult-black-cat': 'Kuroneko~Adult Black Cat~',
    'fake-feat-amuro-namie': 'FAKE (feat. Amuro Namie)',
    'ai-no-uta-majenta-rein': 'Ai no Uta —MAJENTA REIN—',
    'asking-why': 'ASKING WHY',
    'b-wz-you': 'B w/z you',
    'baby-dont-cry': 'Baby Don\'t Cry',
    'cant-sleep-cant-eat-im-sick': 'CAN\'T SLEEP CAN\'T EAT I\'M SICK',
    'can-you-celebrate': 'CAN YOU CELEBRATE?',
    'close-your-eyes-close-to-you': 'Close your eyes, Close to you',
    'dont-lie-to-me': 'Don\'t Lie to Me',
    'dont-wanna-cry': 'Don\'t wanna cry',
    'dr': 'Dr.',
    'first-timer-feat-doberman-inc': 'FIRST TIMER feat. DOBERMAN INC',
    'hide-seek': 'HIDE & SEEK',
    'put-em-up': 'Put \'Em Up!!',
    'sit-stay-wait-down': 'Sit! Stay! Wait! Down!',
    'want-me-want-me': 'WANT ME, WANT ME',
    'tegami-haikei-juugo-no-kimi-e': 'Tegami ~Haikei Juugo no Kimi e~',
    'oashisu-feat-diggy-mo-sould-out': 'OASHISU feat. Diggy-MO\' (SOUL\'d OUT)',
    'lose-your-mind-feat-yutaka-furukawa-from-doping-panda': 'LOSE YOUR MIND feat. Yutaka Furukawa from DOPING PANDA',
    'kimi-eforever-friend': 'Kimi e~forever friend',
    'better-days-feat-katou-miriya-and-tanaka-rouma': 'better days feat. Katou Miriya and Tanaka Rouma',
    'koi-wa-rizumu-believe-my-way-': 'Koi wa RIZUMU -Believe My Way-',
    'i-believe-umi-no-soko-kara': 'I believe ~Umi no Soko kara~',
    'i-shiteru': 'i-shiteru',
    'kakusei-open-your-eyes': 'Kakusei ~open your eyes~',
    'kawaranai-koto-since-1976': 'Kawaranai koto ~since 1976~',
    'kurenai-negai': 'Kurenai ~Negai~',
    'liar-liar-romantic-waltz': 'liar liar ~romantic waltz',
    'life-seimei-no-hibiki': 'life ~Seimei no Hibiki~',
    'love-is-us-love-is-earth': 'Love is Us, Love is Earth',
    'matsu-mabara-na-hikari': 'Matsu ~Mabara na Hikari',
    'moment-ima-wo-ikiru': 'moment ~Ima wo Ikiru~',
    'mou-ichido': 'Mou Ichido...',
    'nesia-no-tabibito-umi-to-kaze-to-hito-no-uta': 'Nesia no Tabibito ~Umi to Kaze to Hito no Uta',
    'new-day-new-life': 'New Day, New Life',
    'new-season-yume-ni-mukatte-fuku-kaze': 'New season ~Yume ni Mukatte Fuku Kaze~',
    'obaa-chan': 'Obaa-chan',
    'one-by-one-day-by-day': 'One by one, Day by day',
    'road-to-glory-for-dragon-nest': 'Road to Glory ~for Dragon Nest',
    'say-hi': 'Say hi!',
    'seinaru-yoru-ni-holly-night': 'Seinaru Yoru ni ~Holly Night',
    'shiro-watashitachi-no-hibiki': 'Shiro ~Watashitachi no Hibiki',
    'sing': '+sing',
    'solace-kioku-no-mori-ni-tsumoru-kaiga': 'Solace ~Kioku no Mori ni Tsumoru Kaiga',
    'something-blue-something-red': 'something blue & something red',
    'sono-mama-de-ii-be-as-you-are': 'Sono Mama de Ii ~be as you are~',
    'sumire-hi-to-tomo-ni': 'Sumire ~Hi to Tomo ni',
    'teo-toriatte-let-us-cling-together': 'Teo Toriatte (Let Us Cling Together)',
    'u-cha-cha': 'U-CHA-CHA',
    'uchuu-ga': 'Uchuu ga...',
    'yoake-rebirth': 'Yoake ~rebirth',
    'yuukyuu-no-mori-my-home-town': 'Yuukyuu no Mori ~My Home Town~',
    'someday-again-mata-au-hi-made': "Someday Again ~Mata Au Hi made~",
    'starstruck-the-return-of-the-luvbytes-feat-ai-hinouchi-emi-and-rum-from-heartsdales': 'STARSTRUCK ~"The Return of the LuvBytes" feat. AI, Hinouchi Emi and Rum from Heartsdales',
    'oshiete-yo-miseducation': 'Oshiete yo ~miseducation~',
    'renai-revolution-21': 'Ren\'ai Revolution 21',
    'where-are-you': 'Where are you?',
    'go-ahead': 'GO AHEAD!!',
    '2330': '23:30',
    'baby-i-love-you': 'Baby, I Love You',
    'amai-wana-paint-it-black': 'Amai Wana ~Paint It Black~',
    'bc': 'B&C',
    'can-you-keep-a-secret': 'Can You Keep a Secret?',
    'cant-wait-til-christmas': 'Can\'t Wait \'Til Christmas'
}